name: peft-vision-transformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=12.1
  - pip
  - pip:
    - transformers==4.36.2
    - peft==0.7.1
    - accelerate==0.25.0
    - timm==0.9.12
    - bitsandbytes==0.41.3
    - datasets==2.16.1
    - numpy==1.24.4
    - pandas==2.1.4
    - scipy==1.11.4
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - plotly==5.17.0
    - pyyaml==6.0.1
    - omegaconf==2.3.0
    - wandb==0.16.1
    - tensorboard==2.15.1
    - pytest==7.4.3
    - pytest-cov==4.1.0
    - black==23.12.1
    - isort==5.13.2
    - flake8==6.1.0
    - mypy==1.8.0
    - jupyter==1.0.0
    - ipykernel==6.27.1
    - notebook==7.0.6
    - psutil==5.9.6
    - memory-profiler==0.61.0
    - scikit-learn==1.3.2
    - statsmodels==0.14.1
    - Pillow==10.1.0
    - opencv-python==4.8.1.78
    - tqdm==4.66.1
    - click==8.1.7
    - rich==13.7.0